matrix: 
 include: 
  - language: java
    before_script:
     - cd Server
    script: mvn test -B
  - language: android
    jdk: oraclejdk8
    android:
      components: 
        - tools
        - android25
        - build-tools-25.0.3
    before_script: 
     - cd Client
    script: gradle build connectedCheck

