matrix: 
 include: 
  - language: java
    before_script:
     - cd Server
    script: mvn test -B
  - language: android
    jdk: oraclejdk8
    android:
      components: 
        - tools
        - android26
        - build-tools-26.0.2
    before_script: 
     - cd Client/MyApplication
    script:
     -  chmod +x gradlew
     - ./gradlew build connectedCheck


