matrix: 
 include: 
  - language: java
    before_script:
     - cd Server
    script: mvn test -B
  - language: android
    jdk: oraclejdk8
    android:
      components: 
        - tools
        - tools
        - platform-tools
        - build-tools-28.0.0
        - android-28.0.0
    before_install:
    - yes | sdkmanager "platforms;android-28"
    before_script: 
     - cd Client/MyApplication
     - chmod +x gradlew
   
    script:
     - ./gradlew build connectedCheck


