matrix: 
 include: 
  - language: java
    before_script:
     - cd Server
     
  - language: android
    jdk: oraclejdk8
      components: 
        - tools
        - android25
        - build-tools-25.0.3
    before_script: 
     - cd Client
