matrix: 
 include: 
  - language: java
    before_script:
     - cd Server
    script: mvn test -B
  - language: android
    jdk: oraclejdk8
    android:
      components: 
        - tools
        - android28
        - build-tools-28.0.0
    before_install:
    - yes | sdkmanager "platforms;android-28"
    before_script: 
     - cd Client/MyApplication
    script:
     -  chmod +x gradlew
     - ./gradlew build connectedCheck


