matrix: 
 include: 
  - language: java
    before_script:
     - cd Server
    script: mvn install -B
  - language: android
    jdk: oraclejdk8
    android:
      components: 
        - tools
        - android26
        - build-tools-26.0.2
    install:
    - chmod +x gradlew
    before_script: 
     - cd Client/MyApplication
    script:
     - ./gradlew test


