env:
  global:
   # Timeout in minutes, default is 2
   - ADB_INSTALL_TIMEOUT=8  
matrix:      # Run both android and java tests
 include: 
  - language: java
    before_script:
     # Root repository directory is not root java project directory.    
     - cd Server          
    # Tell maven to run tests.      
    script: mvn test -B
  - language: android
    # Use the Java Development Kit 8
    jdk: oraclejdk8
    android:
      components: 
        # Install 28.0.3 Built tools, Android 2.8, Android-17 and a 
        # System Image in order to run an Android Emulator running 
        # Android 17
        - build-tools-28.0.3
        - android-28.0.0
        - android-17
        - sys-img-armeabi-v7a-android-17
      licenses:
        # Auto accept licenses.
        - 'android-sdk-license-.+' 
    before_install:
      # Accept some more licenses.
    - yes | sdkmanager "platforms;android-28"
    before_script: 
     # Change root directory to android root.
     - cd Client/MyApplication
     # Give Travis VM permission to use gradlew
     - chmod +x gradlew
     
     # Actually start the emulator.
     - echo no | android create avd --force -n test -t android-17 --abi armeabi-v7a
     - emulator -avd test -no-window &
     - android-wait-for-emulator
     - adb shell input keyevent 82 &
   
    script:
     - android list target
     # Tell gradle to run tests. 
     - ./gradlew build connectedCheck


